version: '3.7'

services:
  app:
    build: .
    container_name: monitoring_app
    working_dir: /app
    volumes:
      - .:/app
    command: python3 app.py
    ports:
      - '5001:5001'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

