version: '3.7'

services:
  app:
    image: retya66/monitoring-app:v3
    container_name: monitoring_app_5001
    working_dir: /app
    ports:
      - '5001:5001'
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_9090
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    depends_on:
      - app

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter_9100
    ports:
      - '9100:9100'
    depends_on:
      - prometheus
    restart: unless-stopped

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter_9115
    ports:
      - '9115:9115'
    depends_on:
      - prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_3000
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  grafana-data:
