version: '3.7'

services:
  app:
    build: .
    container_name: monitoring_app
    working_dir: /app
    volumes:
      - .:/app
    command: python3 app.py
    ports:
      - '5001:5001'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    restart: always

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter_9100
    ports:
      - '9100:9100'
    restart: always
    depends_on:
      - prometheus

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter_9115
    ports:
      - '9115:9115'
    restart: always
    depends_on:
      - prometheus
