version: '3.7'

services:
  app:
    image: retya66/monitoring-app:latest
    container_name: monitoring_app_5001
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '5001:5001'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    restart: always
    depends_on:
      - app

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter_9100
    ports:
      - '9100:9100'
    restart: always
    depends_on:
      - prometheus

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter_9115
    ports:
      - '9115:9115'
    restart: always
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_3000
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-data:
