global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

- job_name: 'node-exporter'
  static_configs:
  - targets: 
    - node-exporter:9100

- job_name: 'blackbox'
  metrics_path: /metrics
  params:
    module: [http_2xx]
  static_configs:
  - targets:
    - app:5001
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter:9115
  