{
 "title": "MONITORING DASHBOARD",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "INFRASTRUCTURE MONITORING", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Idle Time Percentage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Memory Percentage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read/Write Rate  in B/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[5m]) + rate(node_disk_written_bytes_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Disk Read/Write Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total[1m]) + rate(node_disk_writes_completed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inbound & Outbound Network Traffic Rate in B/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[5m]) + rate(node_network_transmit_bytes_total{device=\"eth0\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Speed in Mbps",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_network_speed_bytes * 8) / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "APPLICATION MONITORING", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Application Uptime Status",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\", instance=\"app:5001\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dynamic HTTP Status Code",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"blackbox\", instance=\"app:5001\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "HTTP Request Processing Time (ms)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=\"blackbox\", instance=\"app:5001\", phase=\"processing\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Connection Duration Trend (ms)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=\"blackbox\", phase=\"connect\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}